### ISSUE TITLE
Variable "title" does not exist in "tinypng.imageoptimization.html.twig" at line 4.

### ISSUE THREAD

**Issue by JamesIves** [cdowdy/bolt-tinypng#10]
Getting the error `Variable "title" does not exist in "tinypng.imageoptimization.html.twig" at line 4.` when running this extension and accessing the TinyPNG menu. Running Bolt 3.2.14

**Comment by cdowdy** [comment]
huh... I wonder what changed in Bolt from 3.2.13 to 3.2.14... Thanks for the heads up @JamesIves I'll check a fix pushed here in a bit!

**Comment by JamesIves** [comment]
Excellent, works now! Thanks
