### ISSUE TITLE
PHP 5.6 support

### ISSUE THREAD

**Issue by shyim** [cdowdy/bolt-tinypng#9]
Hey,
the ConfigHelper uses PHP7 Features, but in the composer.json is php7 not required

**Comment by cdowdy** [comment]
Hey @shyim where's the php7 only code?

**Comment by shyim** [comment]
https://github.com/cdowdy/bolt-tinypng/blob/master/src/Helpers/ConfigHelper.php#L155
Returns :)

**Comment by cdowdy** [comment]
@shyim huh well I'll be damned haha... thanks for noticing that .. I never caught that and PHPstorm was being "helpful" haha... much appreciated :)

**Comment by shyim** [comment]
Thank you.❤️   Will you create later a new release?

**Comment by cdowdy** [comment]
@shyim yep just did so it should hit bolt's extension service in a bit.. I'll try to force an update to it too
